# vim:fileencoding=utf-8:foldmethod=marker

background_blur 1
background_opacity 0.8

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME

# auto,x11,wayland
linux_display_server wayland

# no,yes,socket,socket-only,password
allow_remote_control socket
# listen_on unix:/tpm/kitty

# BEGIN_KITTY_FONTS
font_family      family="Source Code Pro"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
